In [75]:
import pandas as pd
import numpy as np
import datetime as dt
import matplotlib.pyplot as plt
import math
from sklearn.preprocessing import MinMaxScaler

In [76]:
dataset=pd.read_csv(r'C:\Users\Farrukh\DNN-Bootcamp\Week-5\Day-21\Daily Demand Forecasting Orders.csv')
dataset.head()

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
0,0,1,4,316.307,223.270,61.543,175.586,302.448,0.000,65556,44914,188411,14793,539.577
1,1,1,5,128.633,96.042,38.058,56.037,130.580,0.000,40419,21399,89461,7679,224.675
2,2,1,6,43.651,84.375,21.826,25.125,82.461,1.386,11992,3452,21305,14947,129.412
3,3,2,2,171.297,127.667,41.542,113.294,162.284,18.156,49971,33703,69054,18423,317.120
4,4,2,3,90.532,113.526,37.679,56.618,116.220,6.459,48534,19646,16411,20257,210.517

In [77]:
scaler = MinMaxScaler()
dataset[dataset.columns] = scaler.fit_transform(dataset)
dataset.columns

Index(['Unnamed: 0',
       'Week of the month (first week, second, third, fourth or fifth week',
       'Day of the week (Monday to Friday)', 'Non-urgent order',
       'Urgent order', 'Order type A', 'Order type B', 'Order type C',
       'Fiscal sector orders', 'Orders from the traffic controller sector',
       'Banking orders (1)', 'Banking orders (2)', 'Banking orders (3)',
       'Target (Total orders)'],
      dtype='object')

In [78]:
dataset.head()

,Unnamed: 0,"Week of the month (first week, second, third, fourth or fifth week",Day of the week (Monday to Friday),Non-urgent order,Urgent order,Order type A,Order type B,Order type C,Fiscal sector orders,Orders from the traffic controller sector,Banking orders (1),Banking orders (2),Banking orders (3),Target (Total orders)
0,0.000000,0.00,0.50,0.696167,1.000000,0.412207,0.621183,1.000000,0.000000,0.896019,0.200245,1.000000,0.107527,0.842157
1,0.016949,0.00,0.75,0.216983,0.127972,0.168466,0.127621,0.246444,0.000000,0.475527,0.086677,0.424709,0.000000,0.195595
2,0.033898,0.00,1.00,0.000000,0.048006,0.000000,0.000000,0.035466,0.001602,0.000000,0.000000,0.028453,0.109855,0.000000
3,0.050847,0.25,0.00,0.325916,0.344732,0.204625,0.364008,0.385450,0.020990,0.635313,0.146101,0.306064,0.162394,0.385405
4,0.067797,0.25,0.25,0.119700,0.247808,0.164532,0.130020,0.183483,0.007467,0.611275,0.078211,0.000000,0.190115,0.166526

In [79]:
import numpy as np
from sklearn.model_selection import train_test_split

# Assuming 'dataset' is your DataFrame

# Separate features and target variable
X = dataset.drop('Target (Total orders)', axis=1).values  # Convert to NumPy array directly
y = dataset['Target (Total orders)']

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=False)

# Reshape for RNN input (assuming time series data)
look_back = 20  # Define your desired lookback period
X_train = np.reshape(X_train, (X_train.shape[0] - look_back, look_back, X_train.shape[1]))
X_test = np.reshape(X_test, (X_test.shape[0] - look_back, look_back, X_test.shape[1]))

ValueError: cannot reshape array of size 624 into shape (28,20,13)

AttributeError: 'DataFrame' object has no attribute 'reshape'